version: "2"

services:
  minio:
    image: minio/minio
    hostname: minio
    environment:
      - MINIO_ACCESS_KEY=access_me
      - MINIO_SECRET_KEY=i_am_a_secret
    volumes:
      - ./minio:/data
    ports:
      - 9000:9000
    command: server /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        while ! /usr/bin/mc config host add minio http://minio:9000 access_me i_am_a_secret;
            do
              sleep 3;
            done;
        /usr/bin/mc mb minio/trino;
      "

  trino:
    image: trinodb/trino
    hostname: trino-host
    ports:
      - 8080:8080
    volumes: 
      - ./trino/etc:/etc/trino
    depends_on: 
      - hive-metastore