version: "2"

services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    volumes:
      - ./mysql:/var/lib/mysql

  minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=accesskey
      - MINIO_SECRET_KEY=secretkey
    volumes:
      - ./minio:/data
    ports:
      - 9000:9000
    command: server /data

  hive-metastore:
    image: hive-metastore:latest
    ports:
    - 9083:9083
    depends_on:
      - mariadb
